TeamCentaur-LiveChat/TeamCentaur-LiveChat/ViewModels/TutorialViewModel.cs
using Crafter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;

namespace TeamCentaur_LiveChat.ViewModels
{
    public class TutorialViewModel
    {

        public int Id { get; set; }
        public string Title { get; set; }

        public static Expression<Func<Tutorial, TutorialViewModel>> FromTutorial
        {
            get
            {
                return (x => new TutorialViewModel() { Id = x.Id, Title = x.Title });
            }
        }
    }
}

TeamCentaur-LiveChat/TeamCentaur-LiveChat/Controllers/TutorialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Crafter.Models;
using Crafter.Data;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using TeamCentaur_LiveChat.Areas.Admin.ViewModels;
using System.IO;
using System.Text.RegularExpressions;
using TeamCentaur_LiveChat.ViewModels;

namespace TeamCentaur_LiveChat.Controllers
{
    public class TutorialsController : Controller
    {
        private CrafterContext db = new CrafterContext();

        // GET: /Tutorials/
        public ActionResult Index()
        {
            return View(db.Tutorials.ToList());
        }

        public JsonResult GetTutorials([DataSourceRequest] DataSourceRequest request, string title)
        {
            var result = this.db.Tutorials.Where(t => t.Title.ToLower().Contains(title.ToLower())).Select(TutorialDisplayModel.FromTutorial).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MyTutorials()
        {
            return View();
        }

        [Authorize]
        public JsonResult GetMyTutorials([DataSourceRequest] DataSourceRequest request)
        {
            var user = this.db.Users.FirstOrDefault(u => u.UserName == HttpContext.User.Identity.Name);

            if (user == null)
            {
                return Json(new List<TutorialDisplayModel>().ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            }

            var tutorials = this.db.Tutorials.Include("Steps").Where(t => t.User.UserName == user.UserName).Select(TutorialDisplayModel.FromTutorial);

            return Json(tutorials.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Search(string tutorialSearch, int? categoryId)
        {
            var result = this.db.Tutorials.AsQueryable();

            if (!string.IsNullOrEmpty(tutorialSearch))
            {
                result = result.Where(t => t.Title.ToLower().Contains(tutorialSearch.ToLower()));
            }
            if (categoryId != null)
            {
                result = result.Where(t => t.Category.Id == categoryId);
            }

            return PartialView("_TutorialsList", result);
        }

        public JsonResult GetCategories([DataSourceRequest] DataSourceRequest request)
        {
            var categories = this.db.Categories.Select(CategoryDisplayModel.FromCategory).ToList();

            return Json(categories, JsonRequestBehavior.AllowGet);
        }

        // GET: /Tutorials/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tutorial tutorial = db.Tutorials.Include("Steps").Include("Comments").FirstOrDefault(t => t.Id == id);
            if (tutorial == null)
            {
                return HttpNotFound();
            }
            return View(tutorial);
        }

        public ActionResult AddComment(int tutorialId, CommentCreateModel commentModel)
        {
            var tutorial = this.db.Tutorials.Find(tutorialId);

            var user = this.db.Users.FirstOrDefault(u => u.UserName == HttpContext.User.Identity.Name);

            if (tutorial == null || !ModelState.IsValid || user == null)
            {
                return Content("");
            }

            Comment newComment = new Comment();
            newComment.Content = commentModel.Content;
            newComment.User = user;
            newComment.CreatedOn = DateTime.Now;
            tutorial.Comments.Add(newComment);
            this.db.SaveChanges();

            return View("_AddComment", newComment);
        }

        public JsonResult CreateTutorial([DataSourceRequest] DataSourceRequest request, TutorialCreateModel tutorialModel)
        {
            var category = this.db.Categories.FirstOrDefault(c => c.Id == tutorialModel.CategoryId);
            var user = this.db.Users.FirstOrDefault(u => u.UserName == HttpContext.User.Identity.Name);

            TutorialDisplayModel result = new TutorialDisplayModel();

            if (tutorialModel != null && user != null)
            {
                Tutorial newTutorial = new Tutorial();
                newTutorial.Category = category;
                newTutorial.CompletionTime = tutorialModel.CompletionTime;
                newTutorial.Description = tutorialModel.Description;
                newTutorial.Difficulty = tutorialModel.Difficulty;
                newTutorial.EquipmentUsed = tutorialModel.EquipmentUsed;
                newTutorial.Title = tutorialModel.Title;
                newTutorial.User = user;
                newTutorial.CreatedOn = DateTime.Now;
                newTutorial.Image = this.GetTutorialImage(newTutorial.Title);

                this.db.Tutorials.Add(newTutorial);
                this.db.SaveChanges();

                result.Category = category.Name;
                result.CategoryId = category.Id;
                result.CompletionTime = newTutorial.CompletionTime;
                result.Id = newTutorial.Id;
                result.CreatedOn = newTutorial.CreatedOn;
                result.Description = newTutorial.Description;
                result.Difficulty = newTutorial.Difficulty;
                result.EquipmentUsed = newTutorial.EquipmentUsed;
                result.Title = newTutorial.Title;
                result.User = user.UserName;
            }

            return Json(new[] { result }.ToDataSourceResult(request, ModelState), JsonRequestBehavior.AllowGet);
        }

        public JsonResult CreateStep([DataSourceRequest] DataSourceRequest request, int tutorialId, StepDisplayModel stepModel)
        {

            var tutorial = this.db.Tutorials.Find(tutorialId);
            var user = this.db.Users.FirstOrDefault(u => u.UserName == HttpContext.User.Identity.Name);

            if (user != tutorial.User)
            {
                ModelState.AddModelError("Permissions", "You don't have permissions");
            }

            if (tutorial != null && user != null && tutorial.User == user && ModelState.IsValid)
            {
                Step step = new Step();
                step.Content = stepModel.Content;
                step.Title = stepModel.Title;

                string newImage = this.GetStepImage(tutorial.Title, step.Title);

                if (newImage != null)
                {
                    step.Image = newImage;
                }

                tutorial.Steps.Add(step);
                db.SaveChanges();
            }

            return Json(new[] { stepModel }.ToDataSourceResult(request, ModelState), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSteps([DataSourceRequest] DataSourceRequest request, int id)
        {
            var tutorial = this.db.Tutorials.Include("Steps").FirstOrDefault(t => t.Id == id);
            var steps = tutorial.Steps.AsQueryable().Select(StepDisplayModel.FromStep);

            return Json(steps.ToDataSourceResult(request, ModelState), JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteStep([DataSourceRequest] DataSourceRequest request, int id, StepDisplayModel stepModel)
        {
            var step = this.db.Steps.Include("Tutorial").FirstOrDefault(st => st.Id == stepModel.Id);
            var tutorial = step.Tutorial;
            var user = tutorial.User;


            if (user.UserName != HttpContext.User.Identity.Name)
            {
                ModelState.AddModelError("Permissions", "You don't have permissions");
                return Json(new[] { stepModel }.ToDataSourceResult(request, ModelState), JsonRequestBehavior.AllowGet);
            }

            if (step != null)
            {
                this.db.Steps.Remove(step);
                this.db.SaveChanges();
            }

            return Json(new[] { stepModel }.ToDataSourceResult(request, ModelState), JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateStep([DataSourceRequest] DataSourceRequest request, StepDisplayModel stepModel)
        {
            var step = this.db.Steps.FirstOrDefault(st => st.Id == stepModel.Id);

            if (step != null && ModelState.IsValid)
            {
                step.Title = stepModel.Title;
                step.Content = stepModel.Content;
                var tutorial = step.Tutorial;

                string newImage = this.GetStepImage(tutorial.Title, step.Title);

                if (newImage != null)
                {
                    step.Image = newImage;
                }

                this.db.SaveChanges();
            }

            return Json(new[] { stepModel }.ToDataSourceResult(request, ModelState), JsonRequestBehavior.AllowGet);
        }


        public ActionResult SaveTutorialImage(IEnumerable<HttpPostedFileBase> files)
        {
            string imageLocation = string.Empty;

            foreach (var file in files)
            {
                string destinationFolder = Server.MapPath("~/Uploaded_Files/Users/" + User.Identity.Name + "/Tutorials/Temp/");
                string extension = Path.GetExtension(file.FileName);

                if (!Directory.Exists(destinationFolder))
                {
                    Directory.CreateDirectory(destinationFolder);
                }

                var destinationPath = destinationFolder + "tutorial-image" + extension;

                file.SaveAs(destinationPath);
            }

            return Content("");
        }

        public ActionResult SaveStepImage(IEnumerable<HttpPostedFileBase> files)
        {
            string imageLocation = string.Empty;

            foreach (var file in files)
            {
                string destinationFolder = Server.MapPath("~/Uploaded_Files/Users/" + User.Identity.Name + "/Steps/Temp/");

TeamCentaur-LiveChat/TeamCentaur-LiveChat/Views/Tutorials/Details.cshtml
@model Crafter.Models.Tutorial

@{
    ViewBag.Title = Model.Title;
}
@*

    <header class="hero-unit clearfix">
        <div class="pull-left">
            <h2>@ViewBag.Title</h2>
            @if (Model.Image != null)
            {
                <img src="@Model.Image" class="img-rounded" />
            }
        </div>
        <div class="pull-right">
            <div>
                <div><strong>Category:</strong><span>@Model.Category.Name</span></div>
                <div><strong>Difficulty:</strong><span>@Model.Difficulty</span></div>
                <div><strong>Completion Time:</strong><span>@Model.CompletionTime</span></div>
                <div><strong>Eqipment Used:</strong><span>@Model.EquipmentUsed</span></div>
                <div><strong>Upload date:</strong><span>@Model.CreatedOn.ToString("yyyy-MMM-dd")</span></div>
                <div><strong>Uploaded by:</strong><span>@Model.User.UserName</span></div>
            </div>
        </div>
    </header>



    <div><strong>Steps:</strong></div>
    <div class="accordion" id="accordion2">

        @for (int i = 0; i < Model.Steps.Count(); i++)
        {
            var step = Model.Steps.ElementAt(i);

            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href=@("#collapse"+ i)>
                        Step @i: @step.Title
                    </a>
                </div>

                <div id=@("collapse" + i) class="accordion-body collapse in">
                    <div class="accordion-inner">
                        <img src="@step.Image" alt="no image" />
                        <div><strong>Description:</strong></div>
                        <div>@step.Content</div>
                    </div>
                </div>
            </div>
        }
    </div>

    <div><strong>Comments:</strong></div>

    <div id="comments">
        @for (int i = 0; i < Model.Comments.Count; i++)
        {
            var comment = Model.Comments.ElementAt(i);

            <div><strong>@comment.User.UserName:</strong><span>@comment.Content</span><div>@comment.CreatedOn.ToString("dd-MMM-yyyy HH:MM:ss")</div></div>
        }


    </div>

    @if (User.Identity.IsAuthenticated)
    {
        <div>
            @using (Ajax.BeginForm("AddComment", new { tutorialId = @Model.Id }, new AjaxOptions
        {
            InsertionMode = InsertionMode.InsertAfter,
            UpdateTargetId = "comments",
            OnSuccess = "clearInput",
            OnFailure = "displayError"
        }))
            {
                <div>
                    <textarea id="comment-input" name="Content"></textarea>
                    <input type="submit" value="Comment" class="k-button" />
                </div>
                <div class="text-error" id="error"></div>
            }
        </div>
    }
*@

<div class="row-fluid">
    <div id="tutorials" class="span8">
        <div class="tutorials-wrapper">
            <div class="row-fluid single-tutorial separate">
                <img src="@Model.Image" style="width:200px; height:200px" class="img-polaroid pull-left" alt="@Model.Category.Name" />

                <div class="tutorial-home-description pull-left">
                    <span class="home-tutorial-category">Category - @Model.Category.Name</span>
                    <h2>@Model.Title</h2>
                    <p class="tutorial-author-and-date">@Model.User.UserName on @Model.CreatedOn.ToString("dd-MMM-yyyy")</p>
                </div>
            </div>

            <div class="row-fluid tutorial-full-description">
                <div class="separate">
                    <h3>Tutorial Details</h3>
                    <p><strong>Equipment used:</strong><span>@Model.EquipmentUsed</span></p>
                    <p><strong>Completion time: </strong><span>@Model.CompletionTime</span></p>
                    <p><strong>Difficulty: </strong><span>@Model.Difficulty</span></p>
                </div>
                <p class="tutorial-description separate">@Model.Description</p>

                <h3>Steps</h3>
                <div class="accordion separate" id="accordion2">

                    @for (int i = 0; i < Model.Steps.Count(); i++)
                    {
                        var step = Model.Steps.ElementAt(i);

                        <div class="accordion-group">
                            <div class="accordion-heading">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href=@("#collapse"+ i)>
                                    Step @i: @step.Title
                                </a>
                            </div>

                            <div id=@("collapse" + i) class="accordion-body collapse in">
                                <div class="accordion-inner">
                                    <img src="@step.Image" alt="no image" />
                                    <div><strong>Description:</strong></div>
                                    <div>@step.Content</div>
                                </div>
                            </div>
                        </div>
                    }
                </div>

                <h3>Comments</h3>

                <div id="comments">
                    @for (int i = 0; i < Model.Comments.Count; i++)
                    {
                        var comment = Model.Comments.ElementAt(i);

                        <div class="single-comment">
                            <strong>@comment.User.UserName</strong>
                            <span>on @comment.CreatedOn.ToString("dd-MMM-yyyy HH:MM:ss")</span>
                            <p>@comment.Content</p>
                        </div>
                    }


                </div>

                @if (User.Identity.IsAuthenticated)
                {
                    <div>
                        @using (Ajax.BeginForm("AddComment", new { tutorialId = @Model.Id }, new AjaxOptions
        {
            InsertionMode = InsertionMode.InsertAfter,
            UpdateTargetId = "comments",
            OnSuccess = "clearInput",
            OnFailure = "displayError"
        }))
                        {
                            <div>
                                <textarea id="comment-input" name="Content"></textarea>
                                <input type="submit" value="Comment" class="k-button" />
                            </div>
                            <div class="text-error" id="error"></div>
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function clearInput() {
        $("#comment-input").val("");
        $("#error").text("");
        $("#menu").kendoMenu();
    }

    function displayError() {
        $("#error").text("Comment must be between 2 and 500 symbols long");
    }
</script>

TeamCentaur-LiveChat/TeamCentaur-LiveChat/Views/Tutorials/Index.cshtml
@model IEnumerable<Crafter.Models.Tutorial>

@{
    ViewBag.Title = "Crafter Tutorials";
}
<div class="row-fluid">
    <div id="tutorials" class="span8">
        @Html.Partial("_TutorialsList", Model);
    </div>

    <div class="span4 home-search">
        @using (Ajax.BeginForm("Search", "Tutorials", new AjaxOptions
        {
            UpdateTargetId = "tutorials",
            InsertionMode = InsertionMode.Replace,
            OnBegin = "beginFade",
            OnComplete = "endFade"
        }))
        {
            <fieldset class="form-horizontal">
                <legend>Search for tutorials</legend>
                <div class="control-group">
                    @Html.Label("Name: ", new { @class = "control-label" })
                    <div class="controls">
                        @(Html.Kendo()
                    .AutoComplete()
                    .Name("tutorialSearch")
                    .DataTextField("Title")
                    .MinLength(3)
                    .Placeholder("Enter tutorial name")
                    .DataSource(source =>
                        {
                            source.Read(read =>
                                {
                                    read.Action("GetTutorials", "Tutorials");
                                    read.Data("tutorialSearch");
                                })
                                .ServerFiltering(true);
                        }
                    ))
                    </div>
                </div>

                <div class="control-group">
                    @Html.Label("Category: ", new { @class = "control-label" })
                    <div class="controls">
                        @(Html.Kendo()
                    .DropDownList()
                    .Name("categoryId")
                    .DataTextField("Name")
                    .DataValueField("Id")
                    .OptionLabel("All")
                    .DataSource(data =>
                    {
                        data.Read(read => read.Action("GetCategories", "Tutorials"));
                        data.ServerFiltering(true);
                    }))
                    </div>
                </div>

                <div class="form-actions no-color">
                    <input type="submit" value="Search" class="k-button pull-right" />
                </div>
            </fieldset>
        }
    </div>
</div>
<script type="text/javascript">
    function tutorialSearch() {
        return {
            title: $("#tutorialSearch").val()
        }
    }

    function beginFade() {
        $("#tutorials").hide();
    }

    function endFade() {
        $("#tutorials").fadeIn(1000);
    }
</script>







@*@model IEnumerable<Crafter.Models.Tutorial>

@{
    ViewBag.Title = "Crafter Tutorials";
}

<h2>@ViewBag.Title</h2>

<div>
    @using (Ajax.BeginForm("Search", "Tutorials", new AjaxOptions
        {
            UpdateTargetId = "tutorials",
            InsertionMode = InsertionMode.Replace,
            OnBegin = "beginFade",
            OnComplete = "endFade"
        }))
    {
        @(Html.Kendo()
    .AutoComplete()
    .Name("tutorialSearch")
    .DataTextField("Title")
    .MinLength(3)
    .Placeholder("Enter tutorial")
    .DataSource(source =>
        {
            source.Read(read =>
                {
                    read.Action("GetTutorials", "Tutorials");
                    read.Data("tutorialSearch");
                })
                .ServerFiltering(true);
        }
    ))

        @(Html.Kendo()
        .DropDownList()
        .Name("categoryId")
        .DataTextField("Name")
        .DataValueField("Id")
        .OptionLabel("All")
        .DataSource(data =>
        {
            data.Read(read => read.Action("GetCategories", "Tutorials"));
            data.ServerFiltering(true);
        }))

        <input type="submit" value="Search" class="k-button" />
    }
</div>

<div id="tutorials" class="row">

    @Html.Partial("_TutorialsList", Model);
</div>

<script type="text/javascript">
    function tutorialSearch() {
        return {
            title: $("#tutorialSearch").val()
        }
    }

    function beginFade() {
        $("#tutorials").fadeOut(70);
    }

    function endFade() {
        $("#tutorials").fadeIn();
    }
</script>*@

TeamCentaur-LiveChat/TeamCentaur-LiveChat/Views/Tutorials/MyTutorials.cshtml
@{
    ViewBag.Title = "MyTutorials";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="span10">
        @(Html.Kendo().Grid<TeamCentaur_LiveChat.Areas.Admin.ViewModels.TutorialDisplayModel>()
    .Name("user-tutorial-grid")
    .Columns(columns =>
    {
        columns.Bound(model => model.Title).Width(250);
        columns.Bound(model => model.Category).Width(150);
        columns.Command(command =>
            {
                command.Edit().Text("Edit Tutorial");
                command.Destroy().Text("Delete Tutorial");
            }).Title("Commands").Width(200);
    })
    .ToolBar(tool =>
        {
            tool.Create().Text("Create Tutorial");
        })
    .Pageable()
    .Sortable(sort =>
        {
            sort.SortMode(GridSortMode.SingleColumn);
        })
        .Editable(edit =>
            {
                edit.Mode(GridEditMode.PopUp);
                edit.TemplateName("TutorialEdit");
            })
    .Groupable()
        .DataSource(data =>
            {
                data.Ajax()
                    .Model(m => m.Id(t => t.Id))
                    .PageSize(10)
                    .ServerOperation(true)
                    .Read("GetMyTutorials", "Tutorials", new { area = "" })
                    .Update("UpdateTutorial", "Admin", new { area = "Admin" })
                    .Destroy("DeleteTutorial", "Admin", new { area = "Admin" })
                    .Create("CreateTutorial", "Tutorials", new { area = "" });
            })
            .ClientDetailTemplateId("details")
        )
    </div>
</div>

<script type="text/kendo-templ" id="details">

    <h5>Steps</h5>
    @(Html.Kendo().Grid<TeamCentaur_LiveChat.Areas.Admin.ViewModels.StepDisplayModel>()
    .Name("steps-grid-#=Id#")
    .Columns(columns =>
    {
        columns.Bound(model => model.Content).Title("Step Content");
        columns.Bound(model => model.Title).Title("Step Title");
        columns.Command(command =>
        {
            command.Edit().Text("Edit Step");
            command.Destroy().Text("Delete Step");
        });
    })
    .ToolBar(t => t.Create().Text("Add Step"))
    .Pageable()
    .Sortable(sort =>
        {
            sort.SortMode(GridSortMode.SingleColumn);
        })
        .Editable(edit =>
            {
                edit.Mode(GridEditMode.PopUp);
                edit.TemplateName("StepEdit");
            })
        .DataSource(data =>
            {
                data.Ajax()
                    .Model(m => m.Id(t => t.Id))
                    .PageSize(10)
                    .ServerOperation(true)
                    .Read("GetSteps", "Tutorials", new { area = "", id = "#=Id#" })
                    .Create("CreateStep", "Tutorials", new { area = "", tutorialId = "#=Id#" })
                    .Update("UpdateStep", "Tutorials", new { area = "" })
                    .Destroy("DeleteStep", "Tutorials", new { area = "", id = "#=Id#" });
            })
    .ToClientTemplate()
    )

</script>